#!/bin/bash

printf "\033c"


#i=1;
while true; do
	

	
	now=`cat /proc/net/dev | awk '{sum = $2} END {print sum }'`
	echo $now
	


	

	cat /proc/uptime | awk '{print $1 " s"}'
	cat /proc/uptime | awk '{print $1/60 " m"}'
	cat /proc/uptime | awk '{print $1/360 " h"}'
	cat /proc/uptime | awk '{print $1/8640 " d"}'

	cat /sys/class/power_supply/BAT1/uevent | awk 'NR==12'

	sleep 1
	#i=$((i+1))
	printf "\033c"

done