#!/bin/bash

stronka=$1
czas=$2

temp=/tmp/webtrace

mkdir $temp

poprzednie=$(cat /dev/urandom | tr -cd 'a-z0-9' | head -c 32)

#Pierwsze pobieranie
wget $stronka -q -O $temp/$poprzednie

sleep $czas

while true; do


  nowe=$(cat /dev/urandom | tr -cd 'a-z0-9' | head -c 32)
  wget $stronka -q -O $temp/$nowe



  roznica=$(diff $temp/$poprzednie $temp/$nowe)


  if [ -n "$roznica" ]; then

    zenity --info --text="Nastąpiła zmiana"

    exit 0

  fi

  poprzednie=$nowe

  sleep $czas

done