#!/bin/bash
location=$1

find $location -type f -exec ./file_info.sh '{}' ';' | sort -n -k1.34 | uniq -D -w32 --all-repeated=separate | tac | cut -f3

#!/bin/bash

file="$1"

md5=$(md5sum "$1" | awk '{ print $1 }')
size=$(stat -c %s "$1")

echo -e "$md5\t$size\t$1"